// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  pairKey: __t.string(),
  score: __t.u32(),
  metricShared: __t.u32(),
  metricComplementary: __t.u32(),
  metricGoals: __t.u32(),
  summary: __t.string(),
  commonGround: __t.string(),
  icebreakers: __t.string(),
};
