// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pairKey: __t.string().primaryKey().name("pair_key"),
  eventId: __t.u64().name("event_id"),
  aIdentity: __t.identity().name("a_identity"),
  bIdentity: __t.identity().name("b_identity"),
  status: __t.string(),
  score: __t.u32(),
  metricShared: __t.u32().name("metric_shared"),
  metricComplementary: __t.u32().name("metric_complementary"),
  metricGoals: __t.u32().name("metric_goals"),
  summary: __t.string(),
  commonGround: __t.string().name("common_ground"),
  icebreakers: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
