// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentMessage = __t.object("AgentMessage", {
  id: __t.u64(),
  pairKey: __t.string(),
  speaker: __t.string(),
  turn: __t.u32(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentMessage = __Infer<typeof AgentMessage>;

export const Attendee = __t.object("Attendee", {
  id: __t.u64(),
  eventId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type Attendee = __Infer<typeof Attendee>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Match = __t.object("Match", {
  pairKey: __t.string(),
  eventId: __t.u64(),
  aIdentity: __t.identity(),
  bIdentity: __t.identity(),
  status: __t.string(),
  score: __t.u32(),
  metricShared: __t.u32(),
  metricComplementary: __t.u32(),
  metricGoals: __t.u32(),
  summary: __t.string(),
  commonGround: __t.string(),
  icebreakers: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Match = __Infer<typeof Match>;

export const Presence = __t.object("Presence", {
  identity: __t.identity(),
  eventId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  facing: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  name: __t.string(),
  goals: __t.string(),
  socials: __t.string(),
  bio: __t.string(),
  persona: __t.string(),
  avatarSeed: __t.string(),
});
export type Profile = __Infer<typeof Profile>;

