// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendAgentTurnReducer from "../append_agent_turn_reducer";
import BeginMatchReducer from "../begin_match_reducer";
import CompleteMatchReducer from "../complete_match_reducer";
import CreateEventReducer from "../create_event_reducer";
import FailMatchReducer from "../fail_match_reducer";
import JoinEventReducer from "../join_event_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import UpsertProfileReducer from "../upsert_profile_reducer";

export type AppendAgentTurnParams = __Infer<typeof AppendAgentTurnReducer>;
export type BeginMatchParams = __Infer<typeof BeginMatchReducer>;
export type CompleteMatchParams = __Infer<typeof CompleteMatchReducer>;
export type CreateEventParams = __Infer<typeof CreateEventReducer>;
export type FailMatchParams = __Infer<typeof FailMatchReducer>;
export type JoinEventParams = __Infer<typeof JoinEventReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type UpsertProfileParams = __Infer<typeof UpsertProfileReducer>;

